name: Build-Test-Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: 'Install packages'
      run: npm ci
    - name: 'Lint'
      run: npm run lint
    - name: 'Build project'
      run: npm run build --if-present
    - name: 'Run tests'
      run: npm test -- --silent
    - name: 'Deploy to Render'
      if: github.ref == 'refs/heads/main'
      env:
        deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK }}
      run: curl "$deploy_url"